kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            default-not-ready-toleration-seconds: "10"
            default-unreachable-toleration-seconds: "10"
            feature-gates: "MutatingAdmissionPolicy=true"
            runtime-config: "admissionregistration.k8s.io/v1beta1=true"
        controllerManager:
          extraArgs:
            feature-gates: "MutatingAdmissionPolicy=true"
        scheduler:
          extraArgs:
            feature-gates: "MutatingAdmissionPolicy=true"
