mergeConfig: true

config: |
  checks:
    runAsRootAllowed: danger
    notReadOnlyRootFilesystem: danger
    privilegeEscalationAllowed: danger
    dangerousCapabilities: danger
    hostPortSet: warning
    cpuRequestsMissing: warning
    memoryRequestsMissing: warning
    cpuLimitsMissing: warning
    memoryLimitsMissing: warning
  mutations:
    - runAsRootAllowed
    - notReadOnlyRootFilesystem
    - privilegeEscalationAllowed
    - dangerousCapabilities
    - cpuRequestsMissing
    - memoryRequestsMissing
    - cpuLimitsMissing
    - memoryLimitsMissing
  exemptions: []

dashboard:
  enable: false

webhook:
  enable: true
  mutate: true
  validate: false
  failurePolicy: Ignore
  timeoutSeconds: 10

certManager:
  apiVersion: cert-manager.io/v1
